# Prefixo mais confortável
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Mouse
set -g mouse on

# Histórico
set -g history-limit 20000

# Visual simples
set -g status-bg black
set -g status-fg green

# Layout inicial
new-session -n shell
new-window -n files "ranger"
new-window -n editor "micro"
